package com.silverline.erp.module.manager.controller;

import com.silverline.erp.common.dto.ApiResponse;
import com.silverline.erp.common.dto.PagedResponse;
import com.silverline.erp.module.analytics.dto.StaffSummaryDTO;
import com.silverline.erp.module.manager.dto.ActivityLogDTO;
import com.silverline.erp.module.manager.dto.ApprovalDTO;
import com.silverline.erp.module.manager.dto.ApprovalUpdateRequest;
import com.silverline.erp.module.manager.service.ManagerService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Slf4j
@RestController
@RequestMapping("/api/v1/manager")
@RequiredArgsConstructor
@Tag(name = "Manager Approvals Dashboard", description = "APIs for managers to monitor staff performance, audit branch activity logs, and process discount/return approval requests")
public class ManagerController {

    private final ManagerService managerService;

    // ===== STAFF SUMMARY =====

    @Operation(summary = "Get branch staff summary list", description = "Retrieves sales statistics, cashier shifts details, and login summaries of all employees in a branch")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Staff summary list fetched successfully")
    @GetMapping("/staff/summary")
    public ResponseEntity<ApiResponse<List<StaffSummaryDTO>>> getStaffSummary(
            @RequestHeader(value = "X-Branch-ID", required = false) Long branchId) {
        log.info("Fetching staff summary for branchId: {}", branchId);
        List<StaffSummaryDTO> staff = managerService.getStaffSummary(branchId);
        return ResponseEntity.ok(ApiResponse.success("Staff summary fetched successfully", staff));
    }

    // ===== APPROVALS =====

    @Operation(summary = "Get branch approvals list", description = "Lists manager approval requests (returns, custom discounts, override alerts) filtered by status and branch headers")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Approvals list fetched successfully")
    @GetMapping("/approvals")
    public ResponseEntity<ApiResponse<List<ApprovalDTO>>> getApprovals(
            @RequestParam(required = false) String status,
            @RequestHeader(value = "X-Branch-ID", required = false) Long branchId) {
        log.info("Fetching approvals with status: {}, branchId: {}", status, branchId);
        List<ApprovalDTO> approvals = managerService.getApprovals(status, branchId);
        return ResponseEntity.ok(ApiResponse.success("Approvals fetched successfully", approvals));
    }

    @Operation(summary = "Get my pending approval requests", description = "Lists override approval requests generated by the current cashier user")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "My approvals list fetched successfully")
    @GetMapping("/approvals/me")
    public ResponseEntity<ApiResponse<List<ApprovalDTO>>> getMyApprovals(
            @RequestHeader(value = "X-Branch-ID", required = false) Long branchId) {
        log.info("Fetching my approval requests for branchId: {}", branchId);
        List<ApprovalDTO> approvals = managerService.getMyApprovals(branchId);
        return ResponseEntity.ok(ApiResponse.success("Your approvals fetched successfully", approvals));
    }

    @Operation(summary = "Update override approval status", description = "Manager reviews and updates status of an override request (approves or rejects discount/return)")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Approval status updated successfully")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "400", description = "Invalid request status state")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "404", description = "Approval record not found")
    @PatchMapping("/approvals/{approvalId}")
    public ResponseEntity<ApiResponse<ApprovalDTO>> updateApprovalStatus(
            @PathVariable Long approvalId,
            @jakarta.validation.Valid @RequestBody ApprovalUpdateRequest request) {
        log.info("Updating approval {} to status: {}", approvalId, request.getStatus());
        ApprovalDTO approval = managerService.updateApprovalStatus(
                approvalId,
                request.getStatus(),
                request.getNotes(),
                request.getRole()
        );
        return ResponseEntity.ok(ApiResponse.success("Approval status updated", approval));
    }

    // ===== BRANCH ACTIVITY LOG =====

    @Operation(summary = "Get branch activity log", description = "Retrieves a paginated list of activity logs filtered by branch headers")
    @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "200", description = "Activity log fetched successfully")
    @GetMapping("/activity-log")
    public ResponseEntity<ApiResponse<PagedResponse<ActivityLogDTO>>> getBranchActivityLog(
            @PageableDefault(size = 20) Pageable pageable,
            @RequestHeader(value = "X-Branch-ID", required = false) Long branchId) {
        log.info("Fetching branch activity log with pageable: {}, branchId: {}", pageable, branchId);
        Page<ActivityLogDTO> pageInfo = managerService.getBranchActivityLog(pageable, branchId);
        return ResponseEntity.ok(ApiResponse.success("Activity log fetched successfully", PagedResponse.from(pageInfo)));
    }
}

