-- V13: Promotions / offers engine. Campaigns are branch-scoped (null = all
-- branches) and evaluated at POS checkout. Multiple promotions may stack.

create table promotions
(
    promotion_id     bigint generated by default as identity,
    name             varchar(150)  not null,
    description      varchar(500),
    promo_type       varchar(30)   not null, -- BUY_X_GET_Y_FREE, PERCENT_OFF, AMOUNT_OFF, N_FOR_FIXED, BUNDLE, EXPIRY_CLEARANCE
    branch_id        bigint,                 -- null = all branches
    scope_type       varchar(20)   not null, -- PRODUCT, CATEGORY, ALL
    scope_ref_id     bigint,                 -- product_id or category_id (null for ALL)
    buy_qty          numeric(15, 3),
    get_qty          numeric(15, 3),
    get_product_id   bigint,                 -- null = same product as bought
    discount_percent numeric(5, 2),
    discount_amount  numeric(15, 2),
    fixed_price      numeric(15, 2),
    min_cart_amount  numeric(15, 2),
    clearance_days   integer,                -- EXPIRY_CLEARANCE: within N days of expiry
    start_at         timestamp(6),
    end_at           timestamp(6),
    priority         integer default 0,
    stackable        boolean default true,
    is_active        boolean default true,
    max_uses         integer,                -- null = unlimited
    uses_count       integer default 0,
    created_by       bigint,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    primary key (promotion_id)
);

create index idx_promotions_branch_active on promotions (branch_id, is_active);

create table promotion_usage
(
    usage_id       bigint generated by default as identity,
    promotion_id   bigint not null,
    sale_id        bigint,
    benefit_amount numeric(15, 2),
    created_at     timestamp(6),
    primary key (usage_id)
);

-- Which promotion (if any) drove a sale line, whether it is a free-giveaway line,
-- and a human-readable reason for the discount.
alter table sale_items
    add column promotion_id bigint;
alter table sale_items
    add column is_free boolean default false;
alter table sale_items
    add column discount_reason varchar(200);
