create table accounts
(
    is_active  boolean,
    account_id bigint generated by default as identity,
    created_at timestamp(6),
    parent_id  bigint,
    code       varchar(20)  not null unique,
    type       varchar(20)  not null,
    name       varchar(120) not null,
    primary key (account_id)
);
create table approvals
(
    approval_id    bigint generated by default as identity,
    approved_at    timestamp(6),
    approved_by    bigint,
    branch_id      bigint      not null,
    created_at     timestamp(6),
    reference_id   bigint,
    requested_by   bigint      not null,
    status         varchar(20),
    type           varchar(50) not null,
    reference_no   varchar(100),
    approval_notes TEXT,
    payload_json   TEXT,
    request_notes  TEXT,
    primary key (approval_id)
);
create table audit_logs
(
    branch_id  bigint,
    created_at timestamp(6),
    log_id     bigint generated by default as identity,
    record_id  bigint,
    user_id    bigint,
    ip_address varchar(45),
    action     varchar(50) not null,
    table_name varchar(100),
    new_values TEXT,
    old_values TEXT,
    user_agent TEXT,
    primary key (log_id)
);
create table batches
(
    cost_price         numeric(15, 2),
    expiry_date        date,
    manufacturing_date date,
    mrp                numeric(15, 2),
    qty                numeric(15, 3),
    selling_price      numeric(15, 2),
    batch_id           bigint generated by default as identity,
    branch_id          bigint      not null,
    created_at         timestamp(6),
    product_id         bigint      not null,
    batch_code         varchar(60) not null,
    primary key (batch_id)
);
create table branch_activities
(
    activity_id bigint generated by default as identity,
    branch_id   bigint       not null,
    created_at  timestamp(6) not null,
    entity_id   bigint,
    user_id     bigint,
    severity    varchar(20),
    status      varchar(20),
    ip_address  varchar(45),
    description varchar(500),
    action_type varchar(255) not null,
    entity_type varchar(255),
    user_agent  TEXT,
    metadata    jsonb,
    primary key (activity_id)
);
create table branches
(
    is_active  boolean,
    branch_id  bigint generated by default as identity,
    created_at timestamp(6),
    updated_at timestamp(6),
    address    varchar(255),
    code       varchar(255) not null unique,
    email      varchar(255),
    location   varchar(255),
    name       varchar(255) not null,
    phone      varchar(255),
    primary key (branch_id)
);
create table brands
(
    is_active   boolean,
    brand_id    bigint generated by default as identity,
    created_at  timestamp(6),
    name        varchar(100) not null,
    description TEXT,
    primary key (brand_id)
);
create table cash_flows
(
    amount       numeric(38, 2),
    created_at   timestamp(6),
    created_by   bigint,
    flow_id      bigint generated by default as identity,
    shift_id     bigint,
    reason       varchar(255),
    reference_no varchar(255),
    status       varchar(255),
    type         varchar(255),
    primary key (flow_id)
);
create table cash_shift_denominations
(
    amount             numeric(15, 2),
    denomination_value numeric(10, 2) not null,
    quantity           integer        not null,
    created_at         timestamp(6),
    denom_id           bigint generated by default as identity,
    shift_id           bigint         not null,
    type               varchar(255)   not null check ((type in ('OPENING', 'CLOSING'))),
    primary key (denom_id)
);
create table cash_shifts
(
    cash_difference numeric(15, 2),
    closing_cash    numeric(15, 2),
    expected_cash   numeric(15, 2),
    opening_cash    numeric(15, 2),
    total_returns   numeric(15, 2),
    total_sales     numeric(15, 2),
    approved_at     timestamp(6),
    approved_by     bigint,
    branch_id       bigint       not null,
    cashier_id      bigint       not null,
    closed_at       timestamp(6),
    created_at      timestamp(6),
    opened_at       timestamp(6) not null,
    shift_id        bigint generated by default as identity,
    updated_at      timestamp(6),
    shift_no        varchar(50) unique,
    notes           TEXT,
    status          varchar(255) check ((status in ('PENDING_APPROVAL', 'OPEN', 'CLOSED', 'SUSPENDED'))),
    primary key (shift_id)
);
create table categories
(
    is_active   boolean,
    category_id bigint generated by default as identity,
    created_at  timestamp(6),
    name        varchar(100) not null,
    description TEXT,
    primary key (category_id)
);
create table customers
(
    date_of_birth   date,
    is_active       boolean,
    loyalty_points  integer,
    total_purchases numeric(15, 2),
    created_at      timestamp(6),
    customer_id     bigint generated by default as identity,
    updated_at      timestamp(6),
    phone           varchar(20) unique,
    code            varchar(30) unique,
    city            varchar(100),
    email           varchar(120),
    name            varchar(150) not null,
    address         varchar(255),
    primary key (customer_id)
);
create table dispatch_payment_requests
(
    amount                    numeric(15, 2) not null,
    branch_id                 bigint         not null,
    created_at                timestamp(6),
    dispatch_id               bigint         not null,
    due_date                  timestamp(6),
    processed_at              timestamp(6),
    processed_by              bigint,
    request_id                bigint generated by default as identity,
    requested_by              bigint,
    supervisor_approved_at    timestamp(6),
    supervisor_approved_by    bigint,
    supplier_id               bigint         not null,
    transferred_at            timestamp(6),
    transferred_to_manager_by bigint,
    updated_at                timestamp(6),
    priority                  varchar(20),
    status                    varchar(30),
    dispatch_no               varchar(50),
    payment_method            varchar(50),
    invoice_no                varchar(100),
    payment_reference         varchar(100),
    supplier_name             varchar(150),
    notes                     TEXT,
    primary key (request_id)
);
create table expense_categories
(
    is_active   boolean,
    category_id bigint generated by default as identity,
    created_at  timestamp(6),
    name        varchar(100) not null unique,
    description varchar(255),
    primary key (category_id)
);
create table expense_payments
(
    amount         numeric(12, 2) not null,
    payment_date   date           not null,
    created_at     timestamp(6),
    created_by     bigint,
    expense_id     bigint         not null,
    payment_id     bigint generated by default as identity,
    payment_method varchar(30),
    reference_no   varchar(100),
    notes          varchar(255),
    primary key (payment_id)
);
create table expenses
(
    amount         numeric(12, 2) not null,
    expense_date   date           not null,
    approved_at    timestamp(6),
    approved_by    bigint,
    branch_id      bigint         not null,
    category_id    bigint         not null,
    created_at     timestamp(6),
    created_by     bigint,
    expense_id     bigint generated by default as identity,
    status         varchar(20),
    payment_method varchar(30),
    expense_no     varchar(50)    not null unique,
    reference_no   varchar(100),
    description    varchar(255),
    primary key (expense_id)
);
create table feature_verification_codes
(
    is_used           boolean,
    verification_code integer      not null,
    created_at        timestamp(6),
    expires_at        timestamp(6) not null,
    hashed_code       bigint       not null,
    id                bigint generated by default as identity,
    action            varchar(20)  not null,
    feature_code      varchar(50)  not null,
    primary key (id)
);
create table item_dispatch_lines
(
    expiry_date      date,
    mrp              numeric(15, 2),
    qty_dispatched   numeric(15, 3) not null,
    selling_price    numeric(15, 2),
    total            numeric(15, 2),
    unit_price       numeric(15, 2) not null,
    batch_id         bigint,
    dispatch_id      bigint         not null,
    dispatch_line_id bigint generated by default as identity,
    product_id       bigint         not null,
    to_branch_id     bigint         not null,
    item_type        varchar(20),
    batch_code       varchar(60),
    serial_no        varchar(100),
    primary key (dispatch_line_id)
);
create table item_dispatches
(
    dispatch_date  date        not null,
    invoice_date   date,
    net_amount     numeric(15, 2),
    total_amount   numeric(15, 2),
    approved_at    timestamp(6),
    approved_by    bigint,
    branch_id      bigint      not null,
    created_at     timestamp(6),
    created_by     bigint,
    dispatch_id    bigint generated by default as identity,
    po_id          bigint,
    supplier_id    bigint      not null,
    status         varchar(20),
    payment_status varchar(30),
    dispatch_no    varchar(50) not null unique,
    invoice_no     varchar(100),
    primary key (dispatch_id)
);
create table journal_entries
(
    entry_date       date        not null,
    total_credit     numeric(15, 2),
    total_debit      numeric(15, 2),
    branch_id        bigint      not null,
    created_at       timestamp(6),
    created_by       bigint,
    journal_id       bigint generated by default as identity,
    posted_at        timestamp(6),
    posted_by        bigint,
    status           varchar(20),
    journal_no       varchar(50) not null unique,
    transaction_type varchar(50),
    reference_no     varchar(100),
    memo             varchar(255),
    primary key (journal_id)
);
create table journal_lines
(
    credit      numeric(15, 2),
    debit       numeric(15, 2),
    account_id  bigint not null,
    journal_id  bigint not null,
    line_id     bigint generated by default as identity,
    description varchar(255),
    primary key (line_id)
);
create table loyalty_otps
(
    created_at  timestamp(6),
    customer_id bigint       not null,
    expires_at  timestamp(6) not null,
    id          bigint generated by default as identity,
    otp_code    varchar(10)  not null,
    primary key (id)
);
create table notification_recipients
(
    is_read         boolean,
    created_at      timestamp(6),
    id              bigint generated by default as identity,
    notification_id bigint not null,
    read_at         timestamp(6),
    user_id         bigint not null,
    primary key (id),
    unique (notification_id, user_id)
);
create table notifications
(
    created_at      timestamp(6),
    created_by      bigint,
    notification_id bigint generated by default as identity,
    reference_id    bigint,
    priority        varchar(20),
    reference_type  varchar(50),
    type            varchar(50)  not null,
    title           varchar(200) not null,
    message         TEXT,
    primary key (notification_id)
);
create table password_reset_requests
(
    created_at        timestamp(6),
    id                bigint generated by default as identity,
    reviewed_at       timestamp(6),
    reviewed_by       bigint,
    user_id           bigint       not null,
    status            varchar(20)  not null,
    username          varchar(100) not null,
    email             varchar(150) not null,
    full_name         varchar(150) not null,
    new_password_hash varchar(200) not null,
    admin_notes       TEXT,
    request_notes     TEXT,
    primary key (id)
);
create table payments
(
    amount       numeric(38, 2),
    created_at   timestamp(6),
    payment_id   bigint generated by default as identity,
    sale_id      bigint,
    bank_name    varchar(255),
    card_last4   varchar(255),
    payment_type varchar(255),
    reference_no varchar(255),
    primary key (payment_id)
);
create table permissions
(
    created_at    timestamp(6),
    permission_id bigint generated by default as identity,
    code          varchar(50)  not null unique,
    module        varchar(50),
    name          varchar(100) not null,
    description   TEXT,
    primary key (permission_id)
);
create table pos_quick_pick_items
(
    branch_id  bigint not null,
    created_at timestamp(6),
    id         bigint generated by default as identity,
    product_id bigint not null,
    primary key (id)
);
create table print_header_footer_settings
(
    branch_id              bigint not null unique,
    created_at             timestamp(6),
    id                     bigint generated by default as identity,
    updated_at             timestamp(6),
    header_contact         varchar(100),
    header_branch_line     varchar(150),
    header_business_name   varchar(150),
    footer_extra_line      varchar(255),
    footer_policy_line     varchar(255),
    footer_powered_by_line varchar(255),
    footer_thank_you_line  varchar(255),
    header_address         varchar(255),
    header_extra_line      varchar(255),
    primary key (id)
);
create table product_serials
(
    batch_id    bigint,
    branch_id   bigint       not null,
    created_at  timestamp(6),
    dispatch_id bigint,
    product_id  bigint       not null,
    sale_id     bigint,
    serial_id   bigint generated by default as identity,
    sold_at     timestamp(6),
    status      varchar(20),
    barcode     varchar(60) unique,
    serial_no   varchar(100) not null unique,
    primary key (serial_id)
);
create table products
(
    cost_price      numeric(15, 2),
    is_active       boolean,
    is_serialized   boolean,
    max_stock_level numeric(15, 3),
    mrp             numeric(15, 2),
    reorder_level   numeric(15, 3),
    selling_price   numeric(15, 2),
    warranty_months integer,
    brand_id        bigint,
    category_id     bigint,
    created_at      timestamp(6),
    product_id      bigint generated by default as identity,
    subcategory_id  bigint,
    unit_id         bigint,
    updated_at      timestamp(6),
    barcode         varchar(60) unique,
    sku             varchar(60)  not null unique,
    name            varchar(150) not null,
    description     TEXT,
    primary key (product_id)
);
create table purchase_order_items
(
    discount       numeric(15, 2),
    mrp            numeric(15, 2),
    qty_dispatched numeric(15, 3),
    qty_ordered    numeric(15, 3) not null,
    selling_price  numeric(15, 2),
    total          numeric(15, 2),
    unit_price     numeric(15, 2) not null,
    po_id          bigint         not null,
    po_item_id     bigint generated by default as identity,
    product_id     bigint         not null,
    primary key (po_item_id)
);
create table purchase_order_payments
(
    amount_paid       numeric(15, 2) not null,
    created_at        timestamp(6),
    paid_at           timestamp(6)   not null,
    paid_by           bigint,
    po_id             bigint         not null,
    po_payment_id     bigint generated by default as identity,
    payment_method    varchar(30)    not null,
    payment_reference varchar(120),
    notes             varchar(500),
    primary key (po_payment_id)
);
create table purchase_orders
(
    discount_amount        numeric(15, 2),
    expected_delivery_date date,
    net_amount             numeric(15, 2),
    paid_amount            numeric(15, 2),
    po_date                date        not null,
    total_amount           numeric(15, 2),
    branch_id              bigint      not null,
    created_at             timestamp(6),
    created_by             bigint,
    paid_at                timestamp(6),
    po_id                  bigint generated by default as identity,
    supplier_id            bigint      not null,
    payment_status         varchar(30),
    status                 varchar(30),
    payment_terms          varchar(50),
    po_no                  varchar(50) not null unique,
    primary key (po_id)
);
create table repair_jobs
(
    estimated_cost      numeric(15, 2),
    final_cost          numeric(15, 2),
    approved_by         bigint,
    branch_id           bigint      not null,
    created_at          timestamp(6),
    created_by          bigint,
    customer_id         bigint      not null,
    repair_id           bigint generated by default as identity,
    technician_id       bigint,
    updated_at          timestamp(6),
    status              varchar(30) check ((status in ('RECEIVED', 'DIAGNOSED', 'IN_PROGRESS', 'WAITING_APPROVAL',
                                                       'READY_FOR_PAYMENT', 'PAID', 'DELIVERED', 'CANCELLED'))),
    repair_no           varchar(50) not null unique,
    device_brand        varchar(100),
    device_model        varchar(100),
    imei_no             varchar(100),
    cost_note           TEXT,
    diagnosis_notes     TEXT,
    problem_description TEXT,
    primary key (repair_id)
);
create table repair_payments
(
    amount         numeric(15, 2) not null,
    created_at     timestamp(6),
    payment_id     bigint generated by default as identity,
    received_by    bigint,
    repair_id      bigint         not null,
    payment_method varchar(30),
    primary key (payment_id)
);
create table repair_status_history
(
    changed_at timestamp(6),
    changed_by bigint,
    history_id bigint generated by default as identity,
    repair_id  bigint not null,
    new_status varchar(30) check ((new_status in
                                   ('RECEIVED', 'DIAGNOSED', 'IN_PROGRESS', 'WAITING_APPROVAL', 'READY_FOR_PAYMENT',
                                    'PAID', 'DELIVERED', 'CANCELLED'))),
    old_status varchar(30) check ((old_status in
                                   ('RECEIVED', 'DIAGNOSED', 'IN_PROGRESS', 'WAITING_APPROVAL', 'READY_FOR_PAYMENT',
                                    'PAID', 'DELIVERED', 'CANCELLED'))),
    notes      TEXT,
    primary key (history_id)
);
create table role_permissions
(
    permission_id bigint      not null,
    role          varchar(40) not null,
    primary key (permission_id, role)
);
create table saas_features
(
    is_active        boolean,
    activated_at     timestamp(6),
    activated_by     bigint,
    created_at       timestamp(6),
    deactivated_at   timestamp(6),
    id               bigint generated by default as identity,
    updated_at       timestamp(6),
    feature_category varchar(20)  not null,
    feature_code     varchar(50)  not null unique,
    feature_name     varchar(100) not null,
    primary key (id)
);
create table sale_items
(
    discount     numeric(10, 2),
    qty          numeric(12, 3),
    total        numeric(10, 2),
    unit_price   numeric(10, 2),
    batch_id     bigint,
    product_id   bigint,
    sale_id      bigint,
    sale_item_id bigint generated by default as identity,
    serial_id    bigint,
    primary key (sale_item_id)
);
create table sale_service_status_history
(
    changed_at timestamp(6),
    changed_by bigint,
    history_id bigint generated by default as identity,
    service_id bigint not null,
    new_status varchar(30) check ((new_status in ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))),
    old_status varchar(30) check ((old_status in ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))),
    notes      TEXT,
    primary key (history_id)
);
create table sale_services
(
    balance_collected     numeric(15, 2),
    installation_required boolean,
    service_charge        numeric(15, 2),
    created_at            timestamp(6),
    sale_id               bigint,
    service_id            bigint generated by default as identity,
    technician_id         bigint,
    updated_at            timestamp(6),
    contact_no            varchar(20),
    service_status        varchar(30) check ((service_status in
                                              ('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))),
    service_type          varchar(50) not null check ((service_type in ('DTV_INSTALLATION', 'DTV_SECOND_CONNECTION',
                                                                        'DTV_SERVICE_ONLY'))),
    customer_name         varchar(150),
    additional_items      TEXT,
    address               TEXT,
    notes                 TEXT,
    primary key (service_id)
);
create table sales
(
    change_amount  numeric(10, 2),
    discount       numeric(10, 2),
    gross_total    numeric(12, 2),
    net_total      numeric(12, 2),
    paid_amount    numeric(12, 2),
    tax_amount     numeric(10, 2),
    branch_id      bigint,
    cashier_id     bigint,
    created_at     timestamp(6),
    customer_id    bigint,
    sale_date      timestamp(6),
    sale_id        bigint generated by default as identity,
    shift_id       bigint,
    invoice_no     varchar(255) unique,
    notes          varchar(255),
    payment_status varchar(255),
    sale_type      varchar(255),
    primary key (sale_id)
);
create table sales_return_items
(
    qty            numeric(15, 3) not null,
    total          numeric(15, 2),
    unit_price     numeric(15, 2),
    product_id     bigint         not null,
    return_id      bigint         not null,
    return_item_id bigint generated by default as identity,
    sale_item_id   bigint         not null,
    primary key (return_item_id)
);
create table sales_returns
(
    total_amount  numeric(15, 2),
    approved_by   bigint,
    branch_id     bigint      not null,
    created_at    timestamp(6),
    created_by    bigint,
    return_date   timestamp(6),
    return_id     bigint generated by default as identity,
    sale_id       bigint      not null,
    shift_id      bigint,
    status        varchar(20),
    refund_method varchar(30),
    return_no     varchar(50) not null unique,
    reason        TEXT,
    primary key (return_id)
);
create table secondary_role_assignments
(
    revoked               boolean      not null,
    assigned_by_branch_id bigint,
    created_at            timestamp(6) not null,
    expires_at            timestamp(6) not null,
    id                    bigint generated by default as identity,
    revoked_at            timestamp(6),
    user_id               bigint       not null,
    secondary_role        varchar(30)  not null,
    reason                varchar(255),
    primary key (id)
);
create table stock
(
    available_qty numeric(15, 3),
    quantity      numeric(15, 3),
    reserved_qty  numeric(15, 3),
    branch_id     bigint not null,
    last_updated  timestamp(6),
    product_id    bigint not null,
    stock_id      bigint generated by default as identity,
    primary key (stock_id),
    constraint unique_branch_product unique (branch_id, product_id)
);
create table stock_transfer
(
    quantity        numeric(10, 2) not null,
    approved_by     bigint,
    approved_time   timestamp(6),
    batch_id        bigint,
    created_at      timestamp(6)   not null,
    from_branch_id  bigint         not null,
    id              bigint generated by default as identity,
    product_id      bigint         not null,
    requested_by    bigint         not null,
    requested_time  timestamp(6)   not null,
    to_branch_id    bigint         not null,
    transfer_date   timestamp(6)   not null,
    updated_at      timestamp(6),
    transfer_status varchar(20)    not null,
    transfer_no     varchar(50)    not null unique,
    remarks         varchar(500),
    primary key (id)
);
create table stock_transfer_item
(
    quantity    numeric(15, 3) not null,
    batch_id    bigint,
    created_at  timestamp(6),
    id          bigint generated by default as identity,
    product_id  bigint         not null,
    transfer_id bigint         not null,
    updated_at  timestamp(6),
    primary key (id)
);
create table subcategories
(
    is_active      boolean,
    category_id    bigint       not null,
    created_at     timestamp(6),
    subcategory_id bigint generated by default as identity,
    name           varchar(100) not null,
    description    TEXT,
    primary key (subcategory_id)
);
create table supplier_branches
(
    discount_percentage numeric(5, 2),
    is_preferred        boolean,
    branch_id           bigint not null,
    created_at          timestamp(6),
    supplier_id         bigint not null,
    notes               TEXT,
    primary key (branch_id, supplier_id)
);
create table supplier_contacts
(
    is_primary  boolean,
    contact_id  bigint generated by default as identity,
    created_at  timestamp(6),
    supplier_id bigint       not null,
    phone       varchar(50),
    designation varchar(150),
    email       varchar(150),
    name        varchar(150) not null,
    primary key (contact_id)
);
create table supplier_ledger
(
    balance          numeric(15, 2),
    credit           numeric(15, 2),
    debit            numeric(15, 2),
    transaction_date date        not null,
    branch_id        bigint      not null,
    created_at       timestamp(6),
    ledger_id        bigint generated by default as identity,
    supplier_id      bigint      not null,
    transaction_type varchar(30) not null,
    reference_no     varchar(100),
    description      TEXT,
    primary key (ledger_id)
);
create table supplier_payment_allocations
(
    amount        numeric(15, 2) not null,
    allocation_id bigint generated by default as identity,
    dispatch_id   bigint         not null,
    payment_id    bigint         not null,
    primary key (allocation_id)
);
create table supplier_payments
(
    amount         numeric(15, 2) not null,
    payment_date   date           not null,
    branch_id      bigint         not null,
    created_at     timestamp(6),
    created_by     bigint,
    payment_id     bigint generated by default as identity,
    supplier_id    bigint         not null,
    payment_method varchar(30),
    payment_no     varchar(50)    not null unique,
    reference_no   varchar(100),
    notes          TEXT,
    primary key (payment_id)
);
create table supplier_performance
(
    delivery_rating integer,
    evaluation_date date   not null,
    overall_rating  numeric(3, 2),
    price_rating    integer,
    quality_rating  integer,
    branch_id       bigint,
    created_at      timestamp(6),
    evaluated_by    bigint,
    performance_id  bigint generated by default as identity,
    supplier_id     bigint not null,
    comments        TEXT,
    primary key (performance_id)
);
create table supplier_products
(
    cost_price          numeric(15, 2) not null,
    is_preferred        boolean,
    moq                 integer,
    created_at          timestamp(6),
    product_id          bigint         not null,
    supplier_id         bigint         not null,
    supplier_product_id bigint generated by default as identity,
    supplier_sku        varchar(100),
    primary key (supplier_product_id)
);
create table suppliers
(
    credit_days    integer,
    credit_limit   numeric(15, 2),
    is_active      boolean,
    created_at     timestamp(6),
    created_by     bigint,
    supplier_id    bigint generated by default as identity,
    updated_at     timestamp(6),
    code           varchar(30)  not null unique,
    mobile         varchar(30),
    phone          varchar(30),
    tax_id         varchar(50),
    city           varchar(100),
    contact_person varchar(100),
    country        varchar(100),
    email          varchar(120),
    name           varchar(150) not null,
    website        varchar(150),
    company_name   varchar(200),
    address_line1  varchar(255),
    address_line2  varchar(255),
    primary key (supplier_id)
);
create table system_settings
(
    created_at    timestamp(6),
    id            bigint generated by default as identity,
    updated_at    timestamp(6),
    updated_by    bigint,
    setting_key   varchar(50)  not null unique,
    setting_value varchar(255) not null,
    primary key (id)
);
create table units
(
    created_at timestamp(6),
    unit_id    bigint generated by default as identity,
    symbol     varchar(10),
    name       varchar(50) not null,
    primary key (unit_id)
);
create table user_activity_log
(
    activity_id   bigint generated by default as identity,
    branch_id     bigint,
    created_at    timestamp(6),
    performed_by  bigint,
    user_id       bigint,
    ip_address    varchar(45),
    activity_type varchar(50) not null,
    description   TEXT,
    user_agent    TEXT,
    primary key (activity_id)
);
create table user_approval_requests
(
    created_at     timestamp(6),
    request_id     bigint generated by default as identity,
    reviewed_at    timestamp(6),
    reviewed_by    bigint,
    user_id        bigint      not null,
    status         varchar(20),
    request_type   varchar(30) not null,
    reason         TEXT,
    reviewer_notes TEXT,
    primary key (request_id)
);
create table user_profiles
(
    email_verified        boolean      not null,
    failed_login_attempts integer      not null,
    must_change_password  boolean      not null,
    approved_at           timestamp(6),
    approved_by           bigint,
    created_at            timestamp(6) not null,
    email_verified_at     timestamp(6),
    last_login            timestamp(6),
    updated_at            timestamp(6),
    user_id               bigint generated by default as identity,
    account_status        varchar(20)  not null check ((account_status in
                                                        ('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'REJECTED'))),
    phone                 varchar(30),
    role                  varchar(40) check ((role in
                                              ('SUPER_ADMIN', 'MANAGER', 'SUPERVISOR', 'CASHIER', 'STORE_KEEPER',
                                               'DTV_TECHNICIAN', 'MOBILE_TECHNICIAN'))),
    employee_id           varchar(50) unique,
    registration_token    varchar(100) unique,
    username              varchar(100) not null unique,
    email                 varchar(150) not null unique,
    full_name             varchar(150) not null,
    password              varchar(200) not null,
    rejection_reason      TEXT,
    primary key (user_id)
);
create table user_sessions
(
    is_active     boolean,
    created_at    timestamp(6),
    expires_at    timestamp(6) not null,
    last_activity timestamp(6),
    session_id    bigint generated by default as identity,
    user_id       bigint       not null,
    ip_address    varchar(45),
    token         varchar(255) not null unique,
    user_agent    TEXT,
    primary key (session_id)
);
create index idx_batch_product_expiry on batches (product_id, expiry_date);
create index idx_cash_shift_branch_status on cash_shifts (branch_id, status);
create index idx_dispatch_branch_status on item_dispatches (branch_id, status);
create index idx_payment_sale_type on payments (sale_id, payment_type);
create index idx_po_payments_po on purchase_order_payments (po_id);
create index idx_po_payments_paid_at on purchase_order_payments (paid_at);
create index idx_sale_item_sale_product on sale_items (sale_id, product_id);
create index idx_sale_branch_date on sales (branch_id, sale_date);
create index idx_user_activity_user_date on user_activity_log (user_id, created_at);
alter table if exists expense_payments add constraint FKcjqfvkhcvhqb6bddwecg25e5k foreign key (expense_id) references expenses;
alter table if exists expenses add constraint FKg7aulw52en8nct0mjq8uut03q foreign key (category_id) references expense_categories;
alter table if exists notification_recipients add constraint FKiuf5qgbttjq6ry57u1dni7qn4 foreign key (notification_id) references notifications;
alter table if exists products add constraint FKa3a4mpsfdf4d2y6r8ra3sc8mv foreign key (brand_id) references brands;
alter table if exists products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories;
alter table if exists products add constraint FKappm930ygdfv4qkkhc05pbr5s foreign key (subcategory_id) references subcategories;
alter table if exists products add constraint FKeex0i50vfsa5imebrfdiyhmp9 foreign key (unit_id) references units;
alter table if exists sales_return_items add constraint FKr2u3qkpydsh695an9alpc5hsd foreign key (return_id) references sales_returns;
alter table if exists stock_transfer add constraint FKom3u7qmtc6gyibr43t2tnu7jn foreign key (approved_by) references user_profiles;
alter table if exists stock_transfer add constraint FKtj67avvnkbswkuecu28hyupxw foreign key (batch_id) references batches;
alter table if exists stock_transfer add constraint FKac05q1cvml5xqghhaa4bghu87 foreign key (from_branch_id) references branches;
alter table if exists stock_transfer add constraint FK67ow5kkxn6ltrslnv0xonp8ts foreign key (product_id) references products;
alter table if exists stock_transfer add constraint FKt62wi58fyy323f4h0liykhy44 foreign key (requested_by) references user_profiles;
alter table if exists stock_transfer add constraint FKkj0umb0k58b3034avvs74xxjq foreign key (to_branch_id) references branches;
alter table if exists stock_transfer_item add constraint FK766dk3wygvvi5o5m387fl89bs foreign key (transfer_id) references stock_transfer;
alter table if exists subcategories add constraint FKiborb6ptvy1t1n3v6klb56l5s foreign key (category_id) references categories;
alter table if exists supplier_branches add constraint FKlam2l7ne3kh70h1pb8r3gk7v5 foreign key (supplier_id) references suppliers;
alter table if exists supplier_contacts add constraint FK1g9gcs0mm7oqmvrwab9jpyg3g foreign key (supplier_id) references suppliers;
alter table if exists user_profiles add constraint FKm95hhwyp5fslnhelagkba458d foreign key (approved_by) references user_profiles;
