-- Data-integrity and persistence hardening.
-- FKs are added NOT VALID so this migration never fails on pre-existing dev rows, while still
-- enforcing referential integrity for every new row. Run `VALIDATE CONSTRAINT` later once data is clean.

-- 1) Referential integrity on the money/stock critical tables.
ALTER TABLE sale_items ADD CONSTRAINT fk_sale_items_sale
    FOREIGN KEY (sale_id) REFERENCES sales (sale_id) NOT VALID;
ALTER TABLE sale_items ADD CONSTRAINT fk_sale_items_product
    FOREIGN KEY (product_id) REFERENCES products (product_id) NOT VALID;
ALTER TABLE payments ADD CONSTRAINT fk_payments_sale
    FOREIGN KEY (sale_id) REFERENCES sales (sale_id) NOT VALID;
ALTER TABLE sales_returns ADD CONSTRAINT fk_sales_returns_sale
    FOREIGN KEY (sale_id) REFERENCES sales (sale_id) NOT VALID;
ALTER TABLE sales_return_items ADD CONSTRAINT fk_return_items_sale_item
    FOREIGN KEY (sale_item_id) REFERENCES sale_items (sale_item_id) NOT VALID;

-- 2) Indexes that match hot query paths.
CREATE INDEX IF NOT EXISTS idx_serial_branch_status ON product_serials (branch_id, status);
CREATE INDEX IF NOT EXISTS idx_returns_sale_id ON sales_returns (sale_id);
CREATE INDEX IF NOT EXISTS idx_expense_date_branch ON expenses (expense_date, branch_id);

-- 3) Persistent stock-adjustment audit trail (replaces the in-memory list that was lost on restart).
CREATE TABLE IF NOT EXISTS stock_adjustments (
    adjustment_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id       BIGINT         NOT NULL,
    product_id      BIGINT         NOT NULL,
    adjustment_type VARCHAR(20)    NOT NULL,
    quantity        NUMERIC(15, 3) NOT NULL,
    quantity_before NUMERIC(15, 3),
    quantity_after  NUMERIC(15, 3),
    reason          VARCHAR(255),
    reference_no    VARCHAR(50),
    created_by      BIGINT,
    created_at      TIMESTAMP(6)   DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_stock_adj_branch_product ON stock_adjustments (branch_id, product_id);
CREATE INDEX IF NOT EXISTS idx_stock_adj_created_at ON stock_adjustments (created_at);

-- 4) Idempotency for sale creation: a client-supplied key makes a retried checkout return the
--    existing sale instead of creating a duplicate. Partial unique index ignores rows without a key.
ALTER TABLE sales ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(80);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sales_idempotency
    ON sales (idempotency_key) WHERE idempotency_key IS NOT NULL;
