-- V9: GRN (Goods Received Note) inbound receiving + per-branch product price list.
-- Fresh GRN tables. Dispatch tables are dropped separately in V10.

create table grn
(
    grn_date       date        not null,
    invoice_date   date,
    net_amount     numeric(15, 2),
    total_amount   numeric(15, 2),
    posted_at      timestamp(6),
    posted_by      bigint,
    branch_id      bigint      not null,
    created_at     timestamp(6),
    received_by    bigint,
    grn_id         bigint generated by default as identity,
    po_id          bigint,
    supplier_id    bigint      not null,
    status         varchar(20),
    payment_status varchar(30),
    grn_no         varchar(50) not null unique,
    invoice_no     varchar(100),
    primary key (grn_id)
);

create table grn_items
(
    expiry_date   date,
    mrp           numeric(15, 2),
    qty_received  numeric(15, 3) not null,
    selling_price numeric(15, 2),
    total         numeric(15, 2),
    unit_price    numeric(15, 2) not null,
    batch_id      bigint,
    grn_id        bigint         not null,
    grn_item_id   bigint generated by default as identity,
    product_id    bigint         not null,
    item_type     varchar(20),
    batch_code    varchar(60),
    serial_no     varchar(100),
    primary key (grn_item_id)
);

create table grn_payment_requests
(
    amount                    numeric(15, 2) not null,
    branch_id                 bigint         not null,
    created_at                timestamp(6),
    grn_id                    bigint         not null,
    due_date                  timestamp(6),
    processed_at              timestamp(6),
    processed_by              bigint,
    request_id                bigint generated by default as identity,
    requested_by              bigint,
    supervisor_approved_at    timestamp(6),
    supervisor_approved_by    bigint,
    supplier_id               bigint         not null,
    transferred_at            timestamp(6),
    transferred_to_manager_by bigint,
    updated_at                timestamp(6),
    priority                  varchar(20),
    status                    varchar(30),
    grn_no                    varchar(50),
    payment_method            varchar(50),
    invoice_no                varchar(100),
    payment_reference         varchar(100),
    supplier_name             varchar(150),
    notes                     TEXT,
    primary key (request_id)
);

create index idx_grn_branch_status on grn (branch_id, status);

-- Per-branch product price and carry list. A branch sells a product only if it
-- has a row here; price is per branch (no global product price).
create table branch_product
(
    is_active          boolean        default true,
    cost_price         numeric(15, 2) default 0,
    selling_price      numeric(15, 2) default 0,
    mrp                numeric(15, 2) default 0,
    reorder_level      numeric(15, 3) default 0,
    added_by_branch_id bigint,
    added_by_user_id   bigint,
    branch_id          bigint         not null,
    branch_product_id  bigint generated by default as identity,
    product_id         bigint         not null,
    created_at         timestamp(6),
    updated_at         timestamp(6),
    primary key (branch_product_id),
    constraint uq_branch_product unique (branch_id, product_id)
);

-- GRN reference on serials. dispatch_id stays until dispatch removal in V10.
alter table product_serials
    add column grn_id bigint;
